#!/usr/bin/env node
'use strict';
// Independent levvol lifecycle probe with an owned loopback server and frozen data.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {startServer,hash}=require('./browser_smoke.cjs');
const args={};for(let i=2;i<process.argv.length;i+=2){if(!process.argv[i].startsWith('--')||!process.argv[i+1])throw new Error('Expected --name value');args[process.argv[i].slice(2)]=process.argv[i+1];}
const root=fs.realpathSync(args.root||path.resolve(__dirname,'..')),out=path.resolve(args.output||fs.mkdtempSync(path.join(os.tmpdir(),'levvol-qa-')));if(args.output)fs.mkdirSync(out);
const mode=args.mode||'suite',base=args.baseline?JSON.parse(fs.readFileSync(args.baseline)):null,fixedTime='2026-10-05T12:00:00Z',dataFile='data/leverage.json',dataBody=fs.readFileSync(path.join(root,dataFile),'utf8'),input=JSON.parse(dataBody),pairIds=input.etfs.map(e=>e.id);
const assert=(v,m)=>{if(!v)throw new Error(m);},same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const report={root,mode,fixedTime,runtime:{node:process.version,chromiumSandbox:true},source:{runnerHash:hash(fs.readFileSync(__filename)),files:{},responses:[]},cases:[],snapshots:{},requests:[],diagnostics:[],injected:[],cleanup:{},limitations:['Chromium desktop/mobile emulation, not native Safari/physical touch/screen reader/IME.','Numerical behavior is compared with two stable pre-change baselines at fixed time and committed data.']};
for(const f of ['index.html','js/tabs/levvol.js','js/switcher.js','js/utils/data.js',dataFile])report.source.files[f]=hash(fs.readFileSync(path.join(root,f)));fs.copyFileSync(__filename,path.join(out,'runner.cjs'));if(args['expected-source'])assert(report.source.files['js/tabs/levvol.js']===args['expected-source'],'frozen levvol source SHA mismatch');
let server,browser,context,page,stage='setup',pending=[],fixture=null,fixtureRequests=0,releases=[],drainPage=null;
const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');
const frame=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function ready(){await page.waitForFunction(()=>{const s=document.getElementById('tab-levvol'),c=window.echarts?.getInstanceByDom(document.getElementById('levvol-chart'));return !s.hidden&&s.getAttribute('aria-busy')!=='true'&&c?.getOption()?.series?.length===5&&document.getElementById('levvol-table').textContent.includes('單日基準');},null,{timeout:30000});await frame();}
async function state(){return page.evaluate(()=>{const s=document.getElementById('tab-levvol'),c=window.echarts?.getInstanceByDom(document.getElementById('levvol-chart'));return {hidden:s.hidden,busy:s.getAttribute('aria-busy'),banner:s.querySelector('.tab-load-error')?.textContent||null,status:document.getElementById('levvol-status').textContent,table:document.getElementById('levvol-table').textContent.trim(),series:c?.getOption()?.series?.length||0};});}
async function snap(){return page.evaluate(()=>{const o=echarts.getInstanceByDom(document.getElementById('levvol-chart')).getOption();return {pair:document.getElementById('levvol-pair').value,choices:[...document.getElementById('levvol-pair').options].map(e=>({value:e.value,text:e.text})),status:document.getElementById('levvol-status').textContent,table:document.getElementById('levvol-table').innerHTML,financial:{series:o.series,xAxis:o.xAxis,yAxis:o.yAxis,grid:o.grid,legend:o.legend,dataZoom:o.dataZoom}};});}
function store(key,value,pointerOracle){report.snapshots[key]=value;if(base){assert(key in base.snapshots,'baseline missing '+key);const expected=structuredClone(base.snapshots[key]);if(pointerOracle!==undefined){const old=expected.financial.xAxis[0].axisPointer.value;assert(value.financial.xAxis[0].axisPointer.value===pointerOracle,'reentry axisPointer does not match preserved themed endValue');expected.financial.xAxis[0].axisPointer.value=pointerOracle;report.interactionOracles||=[];report.interactionOracles.push({key,path:'financial.xAxis[0].axisPointer.value',oldValue:old,expected:pointerOracle,actual:value.financial.xAxis[0].axisPointer.value,reason:'unchanged themed pointer and preserved dataZoom endValue; pointer follows visible range'});}assert(same(value,expected),'numerical/semantic baseline difference '+key);}}
async function newPage(width,handler,bootless=false){if(context){for(const resolve of releases)resolve();await drainPage();await Promise.allSettled(pending);await context.close();}fixture=handler||null;fixtureRequests=0;releases=[];pending=[];const hasTouch=width===390&&!!handler;report.runtime.contexts||=[];report.runtime.contexts.push({stage,width,hasTouch});context=await browser.newContext({viewport:{width,height:width===390?844:900},hasTouch,timezoneId:'UTC'});page=await context.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(45000);await page.clock.setFixedTime(new Date(fixedTime));
const inflight=new Set();let lastLocalActivity=Date.now();page.on('request',r=>{if(r.url().startsWith(server.url+'/')){inflight.add(r);lastLocalActivity=Date.now();}});for(const event of ['requestfinished','requestfailed'])page.on(event,r=>{if(inflight.delete(r))lastLocalActivity=Date.now();});drainPage=async()=>{const began=Date.now();while(inflight.size||Date.now()-lastLocalActivity<550){if(Date.now()-began>10000)throw new Error('Local network did not drain: '+[...inflight].map(r=>r.url()).join(','));await new Promise(r=>setTimeout(r,50));}};const localFixture=!!handler;page.on('console',m=>{if(['error','warning'].includes(m.type()))report.diagnostics.push({stage,type:m.type(),text:m.text(),location:m.location(),fixture:localFixture});});page.on('pageerror',e=>report.diagnostics.push({stage,type:'pageerror',text:e.message,fixture:localFixture}));page.on('requestfailed',r=>report.diagnostics.push({stage,type:'requestfailed',url:r.url(),text:r.failure()?.errorText,fixture:localFixture}));page.on('request',r=>report.requests.push({stage,url:r.url()}));const injection=new Map();const requestStages=new Map();page.on('request',r=>requestStages.set(r,stage));
if(bootless)await page.route('**/js/boot.js',async route=>{const body='// Declared browser QA boot suppression for direct lifecycle observations.';injection.set(route.request(),hash(body));report.injected.push({stage,file:'js/boot.js',status:200,label:'boot suppression',bodyHash:hash(body)});await route.fulfill({contentType:'text/javascript',body});});
if(handler)await page.route('**/data/leverage.json',async route=>{const n=++fixtureRequests,result=await handler(n,route);if(!result)return route.continue();injection.set(route.request(),hash(result.body));report.injected.push({stage,file:dataFile,n,status:result.status||200,label:result.label,bodyHash:hash(result.body)});const {label,...response}=result;try{await route.fulfill({contentType:'application/json',...response});}catch(e){report.injected.push({stage,file:dataFile,n,fulfillError:e.message});}});
page.on('response',r=>{if(!r.url().startsWith(server.url+'/'))return;pending.push((async()=>{const f=new URL(r.url()).pathname.slice(1)||'index.html',item={stage:requestStages.get(r.request())||stage,file:f,status:r.status(),injected:injection.has(r.request())};try{item.httpHash=hash(await r.body());item.expectedHash=item.injected?injection.get(r.request()):hash(fs.readFileSync(path.join(root,f)));item.equal=item.httpHash===item.expectedHash;}catch(e){item.error=e.message;}report.source.responses.push(item);})());});
await page.goto(server.url+'/#tab=levvol',{waitUntil:'domcontentloaded'});if(bootless)await page.evaluate(()=>{document.querySelectorAll('.tab-section').forEach(s=>s.hidden=true);document.getElementById('tab-levvol').hidden=false;});}
const success=(body=dataBody)=>({body,label:'declared leverage success fixture'}),failure=()=>({status:503,body:'declared leverage HTTP503',label:'declared leverage HTTP503 fixture'});
async function held(){return new Promise(resolve=>releases.push(resolve));}
async function waitRequests(n){await page.waitForFunction(()=>true);for(let i=0;i<200;i++){if(fixtureRequests>=n)return;await new Promise(r=>setTimeout(r,50));}throw new Error('Expected '+n+' fixture requests, got '+fixtureRequests);}
async function failReady(){await page.waitForFunction(()=>!!document.querySelector('#tab-levvol .tab-load-error button'),null,{timeout:30000});await frame();const s=await state();assert(s.busy!=='true'&&s.banner,'failure/loading state inconsistent');assert(s.series===0&&!s.table,'failure shows stale or fabricated result');assert(/Unavailable|不可用|失敗/.test(s.status),'failure status not explicit');return s;}
const retry=()=>page.locator('#tab-levvol .tab-load-error button');
async function geometry(){const g=await page.evaluate(()=>{const s=document.getElementById('tab-levvol'),e=s.querySelector('.tab-load-error'),button=e?.querySelector('button'),r=button?.getBoundingClientRect();return {viewport:innerWidth,coarsePointer:matchMedia('(pointer: coarse)').matches,documentWidth:document.documentElement.scrollWidth,banner:e?{client:e.clientWidth,scroll:e.scrollWidth}:null,button:r?{left:r.left,right:r.right,width:r.width,height:r.height}:null};});assert(g.documentWidth<=g.viewport+1,'document overflow');if(g.banner)assert(g.banner.scroll<=g.banner.client+1,'failure banner clipping');if(g.button){assert(g.button.left>=0&&g.button.right<=g.viewport,'retry offscreen');if(g.coarsePointer)assert(g.button.width>=44&&g.button.height>=44,'retry below44px touch target');}return g;}
async function test(name,fn){if(args.case&&!new RegExp(args.case).test(name))return;stage=name;try{const evidence=await fn();report.cases.push({name,status:'PASS',evidence});console.log('PASS '+name);}catch(e){report.cases.push({name,status:'FAIL',reason:e.message,stack:e.stack});console.log('FAIL '+name+': '+e.message);if(page&&!page.isClosed())try{await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});fs.writeFileSync(path.join(out,name+'-state.json'),JSON.stringify(await state(),null,2));}catch{}}await Promise.allSettled(pending);fs.writeFileSync(path.join(out,'progress.json'),JSON.stringify({stage,cases:report.cases},null,2)+'\n');}
(async()=>{try{server=await startServer(root);report.source.serverRoot=server.root;report.source.url=server.url;const p=require(process.env.PLAYWRIGHT_MODULE||'playwright');report.runtime.playwright=require((process.env.PLAYWRIGHT_MODULE||'playwright')+'/package.json').version;browser=await p.chromium.launch({headless:true,chromiumSandbox:true,ignoreDefaultArgs:['--unsafely-disable-devtools-self-xss-warnings','--enable-unsafe-swiftshader']});report.runtime.browser=browser.version();
if(mode==='repro'){
await test('old-init-resolves-before-render-and-hidden-late-render',async()=>{await newPage(1280,async()=>{await held();return success();},true);const early=await page.evaluate(async()=>{window.qaLev=await import('./js/tabs/levvol.js');window.qaResolved=false;await window.qaLev.init();window.qaResolved=true;const c=echarts.getInstanceByDom(document.getElementById('levvol-chart'));return {initResolved:window.qaResolved,series:c?.getOption()?.series?.length||0,status:document.getElementById('levvol-status').textContent};});assert(early.initResolved&&early.series===0,'did not reproduce early init resolution');await waitRequests(1);await page.evaluate(()=>{document.getElementById('tab-levvol').hidden=true;document.getElementById('tab-sector').hidden=false;});releases.shift()();await page.waitForFunction(()=>echarts.getInstanceByDom(document.getElementById('levvol-chart'))?.getOption()?.series?.length===5);const late=await state();assert(late.hidden&&late.series===5,'did not reproduce hidden late render');return {early,late,requests:fixtureRequests};});
await test('old-rejected-promise-retained-no-dispatcher-retry',async()=>{await newPage(1280,async n=>n===1?failure():success());await page.waitForFunction(()=>document.getElementById('levvol-status').textContent.includes('載入失敗'));const before=await state();assert(!before.banner,'old dispatcher unexpectedly provides retry');await page.evaluate(async()=>{const m=await import('./js/tabs/levvol.js');await m.init();});await page.evaluate(()=>new Promise(r=>setTimeout(r,150)));const after=await state();assert(fixtureRequests===1&&after.status.includes('載入失敗'),'did not reproduce retained rejection');return {before,after,requests:fixtureRequests};});
}else{
for(const width of [1280,390]){
await test('normal-all-pairs-'+width,async()=>{await newPage(width);await ready();for(const id of pairIds){await page.locator('#levvol-pair').selectOption(id);await frame();const s=await snap();assert(s.financial.series.map(x=>x.name).join(',')==='w=5,w=21,w=63,w=126,w=252','window list changed');store('normal-'+width+'-'+id,s);}await page.screenshot({path:path.join(out,'normal-'+width+'.png'),fullPage:true});return {pairs:pairIds,geometry:await geometry()};});
await test('theme-and-route-normal-'+width,async()=>{await page.locator('#levvol-pair').selectOption('TQQQ');await frame();await page.evaluate(()=>{const c=echarts.getInstanceByDom(document.getElementById('levvol-chart'));c.dispatchAction({type:'dataZoom',start:20,end:80});c.dispatchAction({type:'legendUnSelect',name:'w=21'});});const before=await snap();assert(before.financial.dataZoom[0].start===20&&before.financial.dataZoom[0].end===80,'interaction did not set requested20/80zoom');assert(before.financial.legend[0].selected['w=21']===false,'interaction did not hide w21');await page.locator('#theme-btn').click();await ready();const themed=await snap();store('theme-'+width,themed);assert(same(before.financial.series.map(s=>s.data),themed.financial.series.map(s=>s.data)),'theme financial change');await page.evaluate(()=>location.hash='#tab=sector');await page.waitForFunction(()=>document.getElementById('tab-levvol').hidden);await page.evaluate(()=>location.hash='#tab=levvol');await ready();if(mode==='baseline'){await page.evaluate(()=>new Promise(r=>setTimeout(r,150)));}const reentered=await snap();const {dataZoom,legend,...reentryFinancial}=reentered.financial;if(mode!=='baseline')assert(themed.financial.xAxis[0].axisPointer.value===themed.financial.dataZoom[0].endValue,'themed axisPointer must equal preserved endValue oracle');store('reentry-'+width,{...reentered,financial:reentryFinancial},mode!=='baseline'?themed.financial.dataZoom[0].endValue:undefined);if(mode!=='baseline'){assert(same(before.financial.dataZoom.map(z=>[z.start,z.end]),reentered.financial.dataZoom.map(z=>[z.start,z.end])),'reentry lost zoom');assert(same(before.financial.legend.map(l=>l.selected),reentered.financial.legend.map(l=>l.selected)),'reentry lost legend');}return {beforeZoom:before.financial.dataZoom,themeZoom:themed.financial.dataZoom,reentryZoom:reentered.financial.dataZoom,beforeLegend:before.financial.legend.map(l=>l.selected),themeLegend:themed.financial.legend.map(l=>l.selected),reentryLegend:reentered.financial.legend.map(l=>l.selected),axisPointerOracle:themed.financial.dataZoom[0].endValue};});
if(mode==='suite'){
await test('first-loading-and-completion-'+width,async()=>{await newPage(width,async()=>{await held();return success();});await waitRequests(1);const during=await state();assert(during.busy==='true'&&during.series===0&&!during.table,'first load ended early or shows result');assert(await page.locator('#levvol-pair').isDisabled(),'pair selector active during unavailable data');releases.shift()();await ready();const done=await state();assert(done.busy!=='true'&&!done.banner,'loading did not complete');return {during,done,requests:fixtureRequests};});
await test('failure-retry-failure-success-dedup-'+width,async()=>{await newPage(width,async n=>{if(n===2)await held();return n<3?failure():success();});const initial=await failReady();assert(fixtureRequests===1,'initial request count');const g=await geometry();await page.screenshot({path:path.join(out,'failure-'+width+'.png'),fullPage:true});await retry().evaluate(b=>{b.click();b.click();b.click();});await waitRequests(2);await page.evaluate(()=>new Promise(r=>setTimeout(r,100)));assert(fixtureRequests===2,'duplicate concurrent retry request');const retryPending=await state();assert(retryPending.busy==='true'&&retryPending.series===0&&!retryPending.table,'retry pending shows result or completed state');releases.shift()();const failedAgain=await failReady();assert(fixtureRequests===2,'failed retry count');await retry().click();await ready();assert(fixtureRequests===3,'success retry request count');const restored=await snap();const expected=base.snapshots['normal-'+width+'-TQQQ'];assert(same(restored,expected),'recovery changed normal financial output');await page.screenshot({path:path.join(out,'recovered-'+width+'.png'),fullPage:true});return {initial,failedAgain,requests:fixtureRequests,geometry:g,retryPending,recovered:true};});
await test('parse-failure-retry-'+width,async()=>{await newPage(width,async n=>n===1?{body:'{ invalid JSON',label:'declared parse failure'}:success());const before=await failReady();await retry().click();await ready();assert(fixtureRequests===2,'parse retry request count');return {before,recovered:true,requests:fixtureRequests};});
await test('away-complete-hidden-return-'+width,async()=>{await newPage(width,async n=>{if(n===1)await held();return success();});await waitRequests(1);await page.evaluate(()=>location.hash='#tab=sector');await page.waitForFunction(()=>document.getElementById('tab-levvol').hidden);const hiddenBefore=await state();releases.shift()();await page.waitForFunction(()=>document.getElementById('tab-levvol').getAttribute('aria-busy')!=='true');const hiddenAfter=await state();assert(hiddenAfter.hidden&&hiddenAfter.series===0&&!hiddenAfter.table,'hidden late completion rendered');await page.evaluate(()=>location.hash='#tab=levvol');await ready();assert(fixtureRequests===2,'hidden completed payload incorrectly cached or route return did not recover');assert(same(await snap(),base.snapshots['normal-'+width+'-TQQQ']),'route return numeric result changed');return {hiddenBefore,hiddenAfter,requests:fixtureRequests,recovered:true};});
await test('away-return-pending-shares-current-load-'+width,async()=>{await newPage(width,async()=>{await held();return success();});await waitRequests(1);await page.evaluate(()=>location.hash='#tab=sector');await page.waitForFunction(()=>document.getElementById('tab-levvol').hidden);await page.evaluate(()=>location.hash='#tab=levvol');await page.waitForFunction(()=>!document.getElementById('tab-levvol').hidden);assert((await state()).busy==='true','pending return incorrectly clears loading');assert(fixtureRequests===1,'pending route return duplicated request');releases.shift()();await ready();assert(fixtureRequests===1,'pending completion duplicated request');return {requests:fixtureRequests,recovered:true};});
}

}
if(mode==='suite'){
for(const width of [1280,390])await test('malformed-shape-failure-retry-'+width,async()=>{const malformed=JSON.parse(dataBody);malformed.etfs=[malformed.etfs.find(e=>e.id==='TQQQ'),null];await newPage(width,async n=>n===1?success(JSON.stringify(malformed)):success());const failed=await failReady();const before=await page.locator('#levvol-pair').evaluate(e=>({built:e.dataset.built,options:[...e.options].map(o=>o.value),disabled:e.disabled}));await retry().click();await ready();const recovered=await snap();report.shapeProbes||={};report.shapeProbes[width]={failed,before,recovered:{choices:recovered.choices,pair:recovered.pair,status:recovered.status},requests:fixtureRequests};assert(same(recovered.choices,base.snapshots['normal-'+width+'-TQQQ'].choices),'good-payload retry retained empty/stale selector options after failed first build');assert(same(recovered,base.snapshots['normal-'+width+'-TQQQ']),'malformed payload recovery altered normal output');await page.locator('#levvol-pair').selectOption('SOXL');await frame();assert(same(await snap(),base.snapshots['normal-'+width+'-SOXL']),'recovered selector cannot choose alternate ETF normally');return report.shapeProbes[width];});
await test('stale-abort-ignored-response-cannot-overwrite',async()=>{const obsolete=JSON.parse(dataBody);obsolete.etfs[0].real=obsolete.etfs[0].real.map(([d,v],i)=>[d,i%3===0?v*1.05:v]);
await newPage(1280,async n=>{if(n===1){await held();return success(JSON.stringify(obsolete));}return success();},true);
await page.evaluate(async()=>{const original=window.fetch;window.fetch=(url,opts={})=>String(url).includes('data/leverage.json')?original(url,{...opts,signal:undefined}):original(url,opts);window.qaLev=await import('./js/tabs/levvol.js');window.qaA=new AbortController();window.qaOld=window.qaLev.init({signal:window.qaA.signal,isCurrent:()=>!window.qaA.signal.aborted}).catch(e=>e.name);});await waitRequests(1);
await page.evaluate(()=>window.qaA.abort());await page.evaluate(async()=>{window.qaB=new AbortController();window.qaNew=window.qaLev.init({signal:window.qaB.signal,isCurrent:()=>!window.qaB.signal.aborted});});await waitRequests(2);await ready();const before=await snap();assert(same(before,base.snapshots['normal-1280-TQQQ']),'new consumer numerical mismatch');const obsoleteResponse=page.waitForResponse(r=>r.url().endsWith('/'+dataFile)&&r.status()===200);releases.shift()();await (await obsoleteResponse).body();await page.evaluate(()=>new Promise(r=>setTimeout(r,150)));const after=await snap();assert(same(before,after),'late obsolete result overwrote newer current state');assert(fixtureRequests===2,'stale probe request count');return {requests:fixtureRequests,lateResponseIgnored:true,fixture:'old data deliberately different; native AbortSignal removed only for leverage request to reproduce a transport that delivers after abort'};});
await test('activation-timeout-retry-and-late-response',async()=>{await newPage(390,async n=>{if(n===1)await held();return success();});await waitRequests(1);await page.waitForFunction(()=>!!document.querySelector('#tab-levvol .tab-load-error button'),null,{timeout:25000});const timedOut=await state();assert(timedOut.busy!=='true'&&timedOut.banner.includes('逾時'),'activation timeout failure state');assert(timedOut.series===0&&!timedOut.table,'timeout shows stale/fabricated result');assert(/Unavailable|載入失敗/.test(timedOut.status)&&!timedOut.status.includes('載入槓桿資料中'),'timeout leaves contradictory local loading state');await retry().click();await ready();const before=await snap();assert(fixtureRequests===2,'timeout retry did not make fresh request');releases.shift()();await page.evaluate(()=>new Promise(r=>setTimeout(r,150)));assert(same(before,await snap()),'late timeout response changed successful retry');return {timedOut,recovered:true,requests:fixtureRequests};});
}
}
await test('served-http-source-identity',async()=>{await drainPage();await Promise.allSettled(pending);const mismatches=report.source.responses.filter(r=>r.status===200&&(!r.equal||(r.file==='js/tabs/levvol.js'&&r.httpHash!==report.source.files[r.file])));assert(!mismatches.length,'HTTP/disk identity mismatch '+JSON.stringify(mismatches));for(const f of Object.keys(report.source.files))assert(report.source.responses.some(r=>r.file===f&&r.equal&&(!r.injected||r.httpHash===report.source.files[f]))||(mode==='repro'&&f==='js/switcher.js'&&report.source.responses.some(r=>r.file===f&&r.equal)), 'missing source identity '+f);return {verifiedResponses:report.source.responses.filter(r=>r.equal).length};});
await test('console-diagnostics',async()=>{for(const d of report.diagnostics){const httpCase=/^failure-retry-failure-success-dedup-(1280|390)$/.test(d.stage)||(mode==='repro'&&d.stage==='old-rejected-promise-retained-no-dispatcher-retry');const parseCase=/^parse-failure-retry-(1280|390)$/.test(d.stage);const timeoutCase=d.stage==='activation-timeout-retry-and-late-response';const shapeCase=/^malformed-shape-failure-retry-(1280|390)$/.test(d.stage);d.expected=d.fixture&&((httpCase&&d.type==='error'&&d.location?.url?.endsWith('/'+dataFile)&&/503/.test(d.text))||(mode==='repro'&&httpCase&&d.type==='error'&&d.text.startsWith('[levvol] load failed'))||(d.type==='warning'&&d.text.startsWith('[tabs] levvol activation failed')&&((httpCase&&/HTTP 503/.test(d.text))||(parseCase&&/SyntaxError/.test(d.text))||(timeoutCase&&/載入逾時/.test(d.text))||(shapeCase&&/TypeError: Cannot read properties of null \(reading 'id'\)/.test(d.text))))||(timeoutCase&&d.type==='requestfailed'&&/ERR_ABORTED/.test(d.text)&&d.url?.endsWith('/'+dataFile)));}const unexpected=report.diagnostics.filter(d=>!d.expected);assert(!unexpected.length,'unexpected diagnostics '+JSON.stringify(unexpected));return {expectedInjected:report.diagnostics.filter(d=>d.expected).length,unexpected:0};});
if(base)await test('baseline-comparison-complete',async()=>{assert(same(Object.keys(base.snapshots),Object.keys(report.snapshots)),'baseline key mismatch');return {equalSnapshots:Object.keys(report.snapshots).length};});
}catch(e){report.cases.push({name:'setup-or-run',status:'FAIL',reason:e.message,stack:e.stack});console.error(e);}finally{for(const resolve of releases)resolve();if(context)await context.close();if(browser){await browser.close();report.cleanup.browserClosed=true;}if(server){await server.close();report.cleanup.serverClosed=true;}report.summary={passed:report.cases.filter(c=>c.status==='PASS').length,total:report.cases.length,failed:report.cases.filter(c=>c.status!=='PASS').map(c=>c.name),expectedDiagnostics:report.diagnostics.filter(d=>d.expected).length,unexpectedDiagnostics:report.diagnostics.filter(d=>!d.expected).length};report.summary.status=report.summary.failed.length?'FAIL':'PASS';save();fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({root,summary:report.summary,cases:report.cases,diagnostics:report.diagnostics,source:{runnerHash:report.source.runnerHash,files:report.source.files,responseCount:report.source.responses.length,mismatches:report.source.responses.filter(r=>r.status===200&&!r.equal)},snapshotCount:Object.keys(report.snapshots).length,interactionOracles:report.interactionOracles,shapeProbe:report.shapeProbe,shapeProbes:report.shapeProbes,cleanup:report.cleanup},null,2)+'\n');console.log(JSON.stringify(report.summary));process.exitCode=report.summary.failed.length?1:0;}})();
