#!/usr/bin/env node
'use strict';
// Scoped sector popup disclosure QA; owns its loopback server and uses declared HTTP fixtures.
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { startServer, hash } = require('./browser_smoke.cjs');
const args = {};
for (let i=2;i<process.argv.length;i+=2) { if (!process.argv[i].startsWith('--') || !process.argv[i+1]) throw new Error('Expected --name value'); args[process.argv[i].slice(2)]=process.argv[i+1]; }
const root=fs.realpathSync(args.root||path.resolve(__dirname,'..'));
const out=path.resolve(args.output||fs.mkdtempSync(path.join(os.tmpdir(),'sector-holdings-qa-')));
if(args.output)fs.mkdirSync(out);
const baselineMode=args.mode==='baseline';
const assert=(v,m)=>{if(!v)throw new Error(m);};
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);
const fixedTime='2026-10-05T12:00:00.000Z';
const input=JSON.parse(fs.readFileSync(path.join(root,'data/sector_holdings.json')));
const etfs=['XLK','XLF','XLV','XLY','XLC','XLI','XLP','XLE','XLU','XLRE','XLB'];
const fixtureFile='data/sector_holdings.json';
const report={root,mode:baselineMode?'baseline':'suite',fixedTime,commands:{argv:process.argv},runtime:{node:process.version,chromiumSandbox:true},source:{runnerHash:hash(fs.readFileSync(__filename)),files:{},responses:[]},cases:[],snapshots:{},requests:[],diagnostics:[],injected:[],cleanup:{},limitations:['Chromium viewport emulation; native Safari, screen reader, physical touch and IME are not covered.','This scoped probe compares unchanged holdings, sorting, returns, full ECharts series/axes and popup MA data at fixed time.']};
for(const f of ['index.html','js/tabs/sector.js','js/switcher.js','js/state.js',fixtureFile,'data/taiwan_sector_index.json',...etfs.map(k=>'data/'+k+'.json')])report.source.files[f]=hash(fs.readFileSync(path.join(root,f)));
fs.copyFileSync(__filename,path.join(out,'runner.cjs'));
const base=args.baseline?JSON.parse(fs.readFileSync(path.resolve(args.baseline))):null;
let server,browser,context,page,stage='setup',pending=[],fixture=null;
const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');
const frame=()=>page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
async function ready(market='us'){await page.waitForFunction(market=>{const s=document.getElementById('tab-sector'),c=window.echarts?.getInstanceByDom(document.getElementById('sector-chart')),t=document.getElementById('sector-status').textContent;return !s.hidden&&c?.getOption()?.series?.[0]?.data?.length&&(market==='us'?t.includes('美股'):t.includes('台股'))&&!t.includes('載入中');},market,{timeout:30000});await frame();}
async function newPage(width,kind){if(context)await context.close();fixture=kind==='normal'?null:kind;pending=[];context=await browser.newContext({viewport:{width,height:width===390?844:900},timezoneId:'UTC'});page=await context.newPage();page.setDefaultTimeout(10000);page.setDefaultNavigationTimeout(45000);await page.clock.setFixedTime(new Date(fixedTime));
page.on('console',m=>{if(['error','warning'].includes(m.type()))report.diagnostics.push({stage,type:m.type(),text:m.text(),location:m.location(),fixture:kind});});page.on('pageerror',e=>report.diagnostics.push({stage,type:'pageerror',text:e.message}));page.on('requestfailed',r=>report.diagnostics.push({stage,type:'requestfailed',url:r.url(),text:r.failure()?.errorText}));page.on('request',r=>report.requests.push({stage,url:r.url()}));
const injectedRequests=new Map();
if(fixture)await page.route('**/data/sector_holdings.json',async route=>{let body,status=200;
if(fixture==='http') {body='declared optional holdings HTTP failure';status=503;}
else if(fixture==='parse')body='{ invalid-json';
else {const obj={...input,data:{...input.data}};if(fixture==='partial')delete obj.data.XLF;if(fixture==='empty')obj.data.XLK=[];body=JSON.stringify(obj);}
injectedRequests.set(route.request(),hash(body));report.injected.push({stage,file:fixtureFile,label:fixture,status,bodyHash:hash(body)});await route.fulfill({status,contentType:'application/json',body});});
page.on('response',r=>{if(!r.url().startsWith(server.url+'/'))return;pending.push((async()=>{const f=new URL(r.url()).pathname.slice(1)||'index.html';const item={stage,file:f,status:r.status(),injected:injectedRequests.has(r.request())};try {item.httpHash=hash(await r.body());if(item.injected){item.expectedHash=injectedRequests.get(r.request());item.equal=item.httpHash===item.expectedHash;}else {item.diskHash=hash(fs.readFileSync(path.join(root,f)));item.equal=item.httpHash===item.diskHash;}}catch(e){item.error=e.message;}report.source.responses.push(item);})());});
await page.goto(server.url+'/#tab=sector',{waitUntil:'domcontentloaded'});await ready();}
async function mainSnap(){return page.evaluate(()=>({charts:['sector-treemap','sector-chart'].map(id=>{const o=echarts.getInstanceByDom(document.getElementById(id)).getOption();return {id,series:o.series,xAxis:o.xAxis,yAxis:o.yAxis,visualMap:o.visualMap,grid:o.grid};}),status:document.getElementById('sector-status').textContent,sort:[...document.querySelectorAll('[data-sector-col]')].filter(e=>e.classList.contains('active')).map(e=>e.dataset.sectorCol),spark:[...document.querySelectorAll('#sector-sparkline-wrap>div')].map(e=>e.title)}));}
async function popup(key){await page.evaluate(async key=>{if(document.getElementById('sector-pop'))document.getElementById('sector-pop-x').click();const c=echarts.getInstanceByDom(document.getElementById('sector-chart')),t=echarts.getInstanceByDom(document.getElementById('sector-treemap'));const items=t.getOption().series[0].data;const idx=items.findIndex(d=>d._key===key);if(idx<0)throw new Error('Unknown key '+key);const coords=c.convertToPixel({xAxisIndex:0,yAxisIndex:0},[idx,2]);const host=document.getElementById('sector-chart');host.parentElement.scrollLeft=Math.max(0,coords[0]-140);},key);
await page.locator('#sector-chart').scrollIntoViewIfNeeded();await frame();
const pos=await page.evaluate(key=>{const c=echarts.getInstanceByDom(document.getElementById('sector-chart')),t=echarts.getInstanceByDom(document.getElementById('sector-treemap'));const idx=t.getOption().series[0].data.findIndex(d=>d._key===key);const p=c.convertToPixel({xAxisIndex:0,yAxisIndex:0},[idx,2]),r=c.getDom().getBoundingClientRect();return {x:r.left+p[0],y:r.top+p[1]};},key);
await page.mouse.click(pos.x,pos.y);await page.locator('#sector-pop').waitFor();await frame();return popupSnap();}
async function popupSnap(){return page.evaluate(()=>{const pop=document.getElementById('sector-pop'),o=echarts.getInstanceByDom(document.getElementById('sector-line-chart')).getOption(),source=pop.querySelector('[data-sector-holdings-source]');return {financial:{header:pop.firstElementChild.firstElementChild.innerText.replace(/\n?✕$/,''),holdings:[...pop.querySelectorAll('a')].map(e=>({text:e.innerText,href:e.getAttribute('href')})),series:o.series,xAxis:o.xAxis,yAxis:o.yAxis,dataZoom:o.dataZoom,legend:o.legend},source:source?{state:source.dataset.sectorHoldingsSource,text:source.textContent}:null};});}
function disclosure(s,expected){if(baselineMode)return;assert(s.source?.state===expected,'source state expected '+expected+' actual '+JSON.stringify(s.source));assert(s.source.text.includes(expected==='loaded'?'Loaded holdings':'Fallback holdings'),'missing explicit source label');assert(!/即時|最新|real.?time|latest/i.test(s.source.text),'claims freshness');if(expected==='fallback')assert(s.source.text.includes('內建'),'fallback must say built-in');}
async function geometry(){return page.evaluate(()=>{const p=document.getElementById('sector-pop'),el=p?.querySelector('[data-sector-holdings-source]');const r=el?.getBoundingClientRect(),panel=p?.firstElementChild;return {viewport:innerWidth,docWidth:document.documentElement.scrollWidth,panel:panel?{client:panel.clientWidth,scroll:panel.scrollWidth}:null,source:r?{left:r.left,right:r.right,width:r.width,client:el.clientWidth,scroll:el.scrollWidth}:null};});}
function checkGeometry(g){assert(g.docWidth<=g.viewport+1,'document horizontal overflow');if(g.source){assert(g.source.left>=0&&g.source.right<=g.viewport,'disclosure outside viewport');assert(g.source.scroll<=g.source.client+1,'disclosure text clipped');}}
function store(key,value){report.snapshots[key]=value;if(base){assert(key in base.snapshots,'baseline snapshot absent '+key);assert(same(base.snapshots[key],value),'before/after financial mismatch '+key);}}
async function test(name,fn){if(args.case&&!new RegExp(args.case).test(name))return;stage=name;try{const evidence=await fn();report.cases.push({name,status:'PASS',evidence});console.log('PASS '+name);}catch(e){report.cases.push({name,status:'FAIL',reason:e.message,stack:e.stack});console.log('FAIL '+name+': '+e.message);if(page&&!page.isClosed())try{await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});fs.writeFileSync(path.join(out,name+'-dom.txt'),await page.locator('body').innerText());}catch{}}await Promise.allSettled(pending);fs.writeFileSync(path.join(out,'progress.json'),JSON.stringify({stage,cases:report.cases},null,2)+'\n');}
(async()=>{try{server=await startServer(root);report.source.serverRoot=server.root;report.source.url=server.url;const p=require(process.env.PLAYWRIGHT_MODULE||'playwright');report.runtime.playwright=require((process.env.PLAYWRIGHT_MODULE||'playwright')+'/package.json').version;browser=await p.chromium.launch({headless:true,chromiumSandbox:true,ignoreDefaultArgs:['--unsafely-disable-devtools-self-xss-warnings','--enable-unsafe-swiftshader']});report.runtime.browser=browser.version();
for(const width of [1280,390]){
await test('normal-'+width,async()=>{await newPage(width,'normal');for(const sort of ['1M','3M','1Y']){await page.locator('[data-sector-col="'+sort+'"]').click();await ready();store('normal-'+width+'-sort-'+sort,await mainSnap());}await page.locator('[data-sector-col="1M"]').click();await ready();for(const key of etfs){const s=await popup(key);disclosure(s,'loaded');store('normal-'+width+'-'+key,s.financial);}const g=await geometry();checkGeometry(g);await page.screenshot({path:path.join(out,'normal-'+width+'-popup.png'),fullPage:true});return {etfs:etfs.length,geometry:g};});
await test('reopen-reentry-theme-'+width,async()=>{const first=await popup('XLK');await page.keyboard.press('Escape');assert(await page.locator('#sector-pop').count()===0,'Escape did not close popup');const reopened=await popup('XLK');assert(same(first,reopened),'popup reopen changed');await page.locator('#sector-pop-x').click();await page.evaluate(()=>location.hash='#tab=stressdash');await page.waitForFunction(()=>document.getElementById('tab-sector').hidden);await page.evaluate(()=>location.hash='#tab=sector');await ready();const returned=await popup('XLK');assert(same(first,returned),'route reentry changed popup');await page.locator('#sector-pop-x').click();await page.locator('#theme-btn').click();await ready();const themed=await popup('XLK');disclosure(themed,'loaded');store('theme-'+width+'-XLK',themed.financial);checkGeometry(await geometry());await page.locator('#sector-pop-x').click();await page.locator('[data-sector-mkt="tw"]').click();await ready('tw');store('tw-'+width,await mainSnap());const tw=await popup('semiconductor');assert(!tw.source,'TW must not have ETF holdings disclosure');store('tw-'+width+'-semiconductor',tw.financial);await page.locator('#sector-pop-x').click();await page.locator('[data-sector-mkt="us"]').click();await ready();disclosure(await popup('XLF'),'loaded');return {reopen:true,reentry:true,theme:true,US_TW:true};});
for(const kind of ['http','parse','partial','empty'])await test(kind+'-'+width,async()=>{await newPage(width,kind);store(kind+'-'+width+'-main',await mainSnap());const states=[];for(const key of ['XLK','XLF']){const s=await popup(key),expected=['http','parse'].includes(kind)||(kind==='partial'&&key==='XLF')?'fallback':'loaded';disclosure(s,expected);store(kind+'-'+width+'-'+key,s.financial);states.push({key,expected,source:s.source,holdings:s.financial.holdings.length});if(kind==='empty'&&key==='XLK')assert(s.financial.holdings.length===0,'truthy empty array must not fallback');checkGeometry(await geometry());}await page.screenshot({path:path.join(out,kind+'-'+width+'-popup.png'),fullPage:true});await page.locator('#sector-pop-x').click();await page.evaluate(()=>location.hash='#tab=stressdash');await page.waitForFunction(()=>document.getElementById('tab-sector').hidden);await page.evaluate(()=>location.hash='#tab=sector');await ready();const reopened=await popup('XLF');disclosure(reopened,['http','parse','partial'].includes(kind)?'fallback':'loaded');return {states,reentry:true};});
}
await test('served-http-source-identity',async()=>{const failures=report.source.responses.filter(r=>r.status===200&&!r.equal);assert(failures.length===0,'served bytes differ '+JSON.stringify(failures));for(const f of Object.keys(report.source.files))assert(report.source.responses.some(r=>r.file===f&&!r.injected&&r.equal),'no verified disk response '+f);return {verifiedResponses:report.source.responses.filter(r=>r.equal).length,fixtures:report.source.responses.filter(r=>r.injected).length};});
await test('console-diagnostics',async()=>{for(const d of report.diagnostics){d.expected=d.type==='error'&&d.fixture==='http'&&d.location?.url?.endsWith('/'+fixtureFile)&&/503/.test(d.text);}const unexpected=report.diagnostics.filter(d=>!d.expected);assert(unexpected.length===0,'unexpected diagnostics '+JSON.stringify(unexpected));return {expectedInjected:report.diagnostics.filter(d=>d.expected).length,unexpected:0};});
if(base)await test('baseline-comparison-complete',async()=>{assert(same(Object.keys(base.snapshots),Object.keys(report.snapshots)),'baseline scenario key mismatch');return {equalSnapshots:Object.keys(report.snapshots).length,baseline:path.resolve(args.baseline)};});
}catch(e){report.cases.push({name:'setup-or-run',status:'FAIL',reason:e.message,stack:e.stack});console.error(e);}finally{if(context)await context.close();if(browser){await browser.close();report.cleanup.browserClosed=true;}if(server){await server.close();report.cleanup.serverClosed=true;}report.summary={passed:report.cases.filter(c=>c.status==='PASS').length,total:report.cases.length,failed:report.cases.filter(c=>c.status!=='PASS').map(c=>c.name),expectedDiagnostics:report.diagnostics.filter(d=>d.expected).length,unexpectedDiagnostics:report.diagnostics.filter(d=>!d.expected).length};report.summary.status=report.summary.failed.length?'FAIL':'PASS';save();fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify({root,summary:report.summary,cases:report.cases,diagnostics:report.diagnostics,source:{runnerHash:report.source.runnerHash,files:report.source.files,responseCount:report.source.responses.length,mismatches:report.source.responses.filter(r=>r.status===200&&!r.equal)},snapshotCount:Object.keys(report.snapshots).length,cleanup:report.cleanup},null,2)+'\n');console.log(JSON.stringify(report.summary));console.log(path.join(out,'report.json'));process.exitCode=report.summary.failed.length?1:0;}})();
